### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by ghost** [GRudinsky/teacozy#3]
https://github.com/GRudinsky/teacozy/blob/master/index.html#L33-L34

Why use an empty `div` tag with a class of `"image"` instead of a regular `img` tag? This is exactly what the `img` tag is for.

https://github.com/GRudinsky/teacozy/blob/master/resources/css/style.css#L92-L106

Nice job including your website's assets (in this case images) in your project and providing a relative file path to them in your `img` tags. 👍 

It's always better to provide static assets up front instead of depending on external URLs that could fail or otherwise become unavailable.

**Comment by GRudinsky** [comment]
This has since been fixed in Colmar Academy project.
