### ISSUE TITLE
Classes and IDs

### ISSUE THREAD

**Issue by ghost** [GRudinsky/teacozy#4]
https://github.com/GRudinsky/teacozy/blob/master/index.html#L32-L56

It'd be best to use the tag that best represents the type of content you're writing. For example:

If you're using an image, use an `img` tag. If you're using a paragraph, use a `p` tag. There's no need to write "image" or "paragraph" in class names when the HTML tag already indicates this purpose.

You've also got your IDs and Classes mixed up. Use an ID for an element that needs to be identified individually. Use a class to group multiple similar elements. If you're going to use `"featured"` for every tea, you should use it as a class. Then `"berry"`, `"spiced"`, etc. can be the IDs that identify a single tea element on the page.

Same for your locations section.

**Comment by GRudinsky** [comment]
All the fixes have since been addressed and fixed in Colmar Academy Project
